### PR TITLE
Run tests

### PR DESCRIPTION
**Pull request by eriknw**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* ~[ ] Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

These tests run very fast. We have been experiencing issues wrapping variadic functions in CFFI on arm64, which the tests should catch.

### CODE REVIEW

**Comment by eriknw** [comment]
@conda-forge-admin, please rerender

**Comment by eriknw** [comment]
Huh, I was expecting some tests to fail for `osx_arm64`.  Well, it's good to have more tests, so I'm merging.

**Comment by jakirkham** [comment]
We [skip the tests when cross-compiling]( https://github.com/conda-forge/python-suitesparse-graphblas-feedstock/blob/4bda1afb97ce9fa3e1b0485c374ef74fbf5259f0/.scripts/run_osx_build.sh#L59-L61 ).

**Comment by eriknw** [comment]
> We [skip the tests when cross-compiling](https://github.com/conda-forge/python-suitesparse-graphblas-feedstock/blob/4bda1afb97ce9fa3e1b0485c374ef74fbf5259f0/.scripts/run_osx_build.sh#L59-L61).

Dope. Of course. That's what you've been saying. My bad. I need a nap.

Thanks again for your help @jakirkham.

@jim22k is seeing an issue with C variadic functions in CFFI on osx arm64. Maybe he can provide more detail.

**Comment by jakirkham** [comment]
Naps are great! No worries. Happy to help 🙂

**Pull request merged**
